[package]
name = "os-simulator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "os-simulator"
path = "src/main.rs"

[lib]
name = "os_simulator"
path = "src/lib.rs"

[dependencies]
rand = "0.8"
chrono = "0.4"
